### PR TITLE
Fix test suite heading

### PR DESCRIPTION
**Pull request by dcalhoun**
The documentation included two "Test Suite 4" headings. In reality there are five test suites.

### CODE REVIEW

**Comment by dcalhoun** [comment]
I believe our Release Wrangling schedule does not include the fifth test suite. We likely need to expand the rotation.

**Review by mchowning — APPROVED** [review]
Good catch!

**Comment by mchowning** [comment]
👋  @antonis ! It looks like we were missing one of the test suites (the newly renamed "Test Suite 5") in our release rotations since we had two "Test Suite 4" suites here. Curious if you know any additional context around this.

**Comment by antonis** [comment]
Thank you for the ping @mchowning and noticing the issue @dcalhoun 🙇 
The new test cases were [added recently](https://github.com/wordpress-mobile/test-cases/commit/5719dcb3522ebee5e6ec1400c563e524bc29e894) and were not included in the last rotation plan update (ref: `P9ugOq-1tO-p2`) 😬 
I'll make sure the plan is updated to include `Test Suite 5`.

**Pull request merged**
